"use client";
import {displayTitle} from "../../core/display-labels";
import {ChevronRight,FileText,Layers3,Orbit} from 'lucide-react';
import {useRuntime} from '../../core/runtime-context';
import {text,type Entity} from '../live/types';
export function MentionPicker({query,busy,onPersonal,onResource,onDismiss}:{query:string;busy:boolean;onPersonal:()=>void;onResource:(item:Entity)=>void;onDismiss:()=>void}){
 const runtime=useRuntime()!,snapshot=runtime.snapshot!,keyword=query.trim().toLocaleLowerCase();
 const resources=keyword?[...snapshot.objects.skill,...snapshot.objects.document,...snapshot.objects.knowledge,...snapshot.objects.resource].filter(item=>!['archived','deleted','rejected','superseded','expired','needs_review'].includes(text(item,'status'))&&[text(item,'title'),text(item,'name'),text(item,'instructions')].join(' ').toLocaleLowerCase().includes(keyword)).slice(0,4):[];
 return <section id="elfred-mention-picker" className="elfred-mention-picker" aria-label="选择调用对象" onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();onDismiss()}}}><p className="elfred-mention-title">选择调用对象</p><button type="button" className="elfred-mention-personal" disabled={busy} onMouseDown={event=>event.preventDefault()} onClick={onPersonal}><span className="elfred-mention-logo"><Orbit size={24} strokeWidth={1.5}/></span><span className="elfred-mention-identity"><strong>我的 Elfred</strong><small>私下帮我整理，不会替我发消息</small></span><ChevronRight className="elfred-mention-chevron" size={18}/></button>{keyword&&<div className="elfred-mention-results">{resources.length?resources.map(item=><button type="button" key={item.id} disabled={busy} onMouseDown={event=>event.preventDefault()} onClick={()=>onResource(item)}>{item.type==='skill'?<Layers3 size={18}/>:<FileText size={18}/>}<span><strong>{displayTitle(text(item,'title'),'')||text(item,'name')}</strong><small>{item.type==='skill'?'技能':'资料'}</small></span></button>):<p>没有匹配的资料或技能</p>}</div>}{!keyword&&<p className="elfred-mention-simple-hint">继续输入可搜索资料和技能</p>}</section>;
}
