"use client";
import {useState,type FormEvent} from 'react';
import {useRuntime} from './runtime-context';

export function AccountForm({identifier,onBack}:{identifier:string;onBack:()=>void}){
  const runtime=useRuntime()!;
  const [register,setRegister]=useState(false),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const submit=async(event:FormEvent)=>{event.preventDefault();if(busy)return;if(register&&password!==confirmation){setError('两次密码不一致，请重新输入');return;}setError('');setBusy(true);try{await runtime.login(identifier,password,register);}catch(reason){setError(reason instanceof Error?reason.message:'暂时无法连接，请重试');}finally{setBusy(false);}};
  const changeMode=(value:boolean)=>{setRegister(value);setError('');runtime.clearError();setConfirmation('');};
  return <main className="v280-onboarding-page"><header className="v277-app-header"><button type="button" className="v277-icon-button" aria-label="返回账号输入" disabled={busy} onClick={onBack}>←</button><h1>{register?'创建 Elfred 账号':'登录 Elfred'}</h1></header><section className="v280-step-copy"><h2>{identifier}</h2><p>用密码登录。手机号或邮箱作为账号，不会发送验证码。</p></section><form className="v280-login-form" onSubmit={event=>void submit(event)}><div className="v280-auth-tabs" role="group" aria-label="账号操作"><button type="button" className={register?'v277-secondary':'v277-primary'} aria-pressed={!register} disabled={busy} onClick={()=>changeMode(false)}>登录</button><button type="button" className={register?'v277-primary':'v277-secondary'} aria-pressed={register} disabled={busy} onClick={()=>changeMode(true)}>注册新账号</button></div><label><span>密码（8—128 位）</span><input type="password" aria-label="账号密码" minLength={8} maxLength={128} required value={password} autoComplete={register?'new-password':'current-password'} onChange={event=>{setPassword(event.target.value);setError('');}}/></label>{register&&<label><span>再次输入密码</span><input type="password" aria-label="确认密码" minLength={8} maxLength={128} required value={confirmation} autoComplete="new-password" onChange={event=>{setConfirmation(event.target.value);setError('');}}/></label>}{error&&<p role="alert">{error}{/已注册/.test(error)&&<button type="button" className="v-text" onClick={()=>changeMode(false)}>去登录</button>}</p>}<button type="submit" className="v277-primary" disabled={busy||password.length<8||register&&!confirmation}>{busy?'正在处理…':register?'创建账号并继续':'登录并继续'}</button></form></main>;
}
