"use client";
import {displayTitle} from "../../core/display-labels";
import {useState} from 'react';
import {useRuntime,entityRef} from '../../core/runtime-context';
import {Action,Field} from '../../core/runtime-panels';
import {AttachmentList,type FileRef} from '../live/attachments';
import {type Entity,text} from '../live/types';
import type {Screen} from '../../core/screen';
import './feed-details.css';
export function FeedDetails({item,go}:{item:Entity;go:(screen:Screen)=>void}){
 const r=useRuntime()!,[goal,setGoal]=useState(''),[system,setSystem]=useState(text(item,'system')),[peerSystem,setPeerSystem]=useState(''),[note,setNote]=useState(''),[kind,setKind]=useState('content_error'),s=r.snapshot!;
 const feedback=s.objects.feedback.filter(f=>f.data.feed_id===item.id),comments=[...((item.data.comments||[]) as {id:string;system:string;content:string}[]),...feedback.filter(f=>f.data.kind==='agent_response').map(f=>({id:f.id,system:text(f,'system'),content:text(f,'content')}))];
 const attachments=((item.data.attachments||[]) as FileRef[]).filter(f=>s.objects.attachment.some(a=>a.id===f.id));
 const artifact=s.objects.knowledge.find(k=>k.id===item.data.artifact_id),links=[...new Set((text(artifact,'content').match(/https?:\/\/[^\s<>"）)\]]+/g)||[]))].slice(0,8);
 const peers=s.systems.filter(agent=>agent.id!==item.data.system),selectedPeer=peerSystem||peers[0]?.id;
 return <>{Boolean(item.data.external_url)&&<p><a href={text(item,'external_url')} target="_blank" rel="noreferrer">查看原始来源</a> · 订阅内容尚需核对</p>}{((item.data.citations||[]) as {url:string;title:string}[]).map((c,i)=><p key={i}><a href={c.url} target="_blank" rel="noreferrer">{displayTitle(c.title,'')}</a></p>)}<AttachmentList items={attachments}/><section className="elfred-peer-comment"><b>请另一位 Agent 评论这条动态</b><select aria-label="邀请评论的 Agent" value={selectedPeer} onChange={event=>setPeerSystem(event.target.value)}>{peers.map(agent=><option key={agent.id} value={agent.id}>{agent.name}</option>)}</select><Action disabled={!selectedPeer} run={async()=>{const task=await r.command('feed.question',{...entityRef(item),goal:'请从你的专业角度评论这条动态，补充依据、提出不同看法或需要核对的问题；不要编造已完成的行动。',system:selectedPeer});go({name:'task',id:task.id})}}>准备评论，核对后运行</Action><small>评论经本人验收后才会出现；后续 Agent 可以参考已有评论继续讨论。</small></section>{links.length>0&&<details><summary>成果中引用的链接</summary>{links.map(url=><p key={url}><a href={url} target="_blank" rel="noreferrer">{url}</a></p>)}<small>链接来自成果正文，尚不代表已独立核验。</small></details>}<details><summary>依据、相关性与协作讨论{comments.length?' · '+comments.length:''}</summary><p>{text(item,'reason')||'来自本人验收的任务结果'}</p><p>对应目标：{text(item,'personal_value')||displayTitle(text(item,'title'),'')}</p><p>{text(item,'uncertainty')||'结论应回到原任务与来源核对'}</p>{Boolean(item.data.task_id)&&<button onClick={()=>go({name:'task',id:text(item,'task_id')})}>查看来源与专业能力</button>}{comments.map(c=><article key={c.id}><b>{s.systems.find(a=>a.id===c.system)?.name||'协作系统'} · 模型建议</b><p style={{whiteSpace:'pre-wrap'}}>{c.content}</p></article>)}<Field name="继续追问或请其他 Agent 补充" area value={goal} onChange={setGoal}/><select aria-label="负责补充的系统" value={system} onChange={e=>setSystem(e.target.value)}>{s.systems.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><Action disabled={!goal.trim()} run={async()=>{const task=await r.command('feed.question',{...entityRef(item),goal,system});go({name:'task',id:task.id})}}>准备追问任务，核对后运行</Action><p>验收后的补充归入此事件讨论，不重复生成主帖。</p></details><details><summary>反馈内容或调整方向</summary><select value={kind} onChange={e=>setKind(e.target.value)}><option value="content_error">内容有误</option><option value="understanding_correction">理解需要纠正</option><option value="direction">调整关注方向</option></select><Field name="具体说明" area value={note} onChange={setNote}/><Action disabled={!note.trim()} run={async()=>{await r.command('feed.feedback',{...entityRef(item),kind,note});setNote('')}}>保存本人反馈</Action>{feedback.filter(f=>f.data.kind!=='agent_response').map(f=><p key={f.id}>{text(f,'content')}</p>)}<p>反馈保留来源，不会自动形成稳定画像；相关理解可从“更多”中核对。</p></details></>;
}
