"use client";
import {displayTitle} from "../../core/display-labels";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {ArrowLeft,Sparkles,Compass,Lightbulb,PenLine,Link2,CheckCircle2,ChevronRight} from 'lucide-react';
import {useRuntime} from '../../core/runtime-context';
import {onboardingGuides} from '../../core/onboarding-guides.mjs';
import {alignmentQuestions,alignmentSummary,firstValueChoices} from '../../core/onboarding-choice.mjs';
import {text,statuses} from '../live/types';
import {finalReceipts} from '../../core/result-output';
import {MarkdownContent} from '../../core/markdown-content';
import type {Screen} from '../../core/screen';
import './onboarding-conversation.css';

const icons=[Compass,Lightbulb,PenLine,Link2,CheckCircle2];
const nameOf=(id:string)=>id==='owner'?'Person Agent':onboardingGuides.find(g=>g.id===id)?.name||id;
type Answers=Record<string,{option:string;at:string;scope:string}>;
export function OnboardingConversation({go,onExit}:{go:(screen:Screen)=>void;onExit:()=>void}){
 const runtime=useRuntime()!,snapshot=runtime.snapshot!,session=snapshot.objects.onboarding[0];
 const [busy,setBusy]=useState(false),[taskChoice,setTaskChoice]=useState('outline'),[interestInput,setInterestInput]=useState(''),[groupInput,setGroupInput]=useState(''),lock=useRef(false),stream=useRef<HTMLElement>(null),questionNode=useRef<HTMLElement>(null);
 const data=session.data,mode=text(session,'choice_mode')||'sequential',phase=text(session,'choice_phase')||'intro';
 const step=Number(data.choice_step)||0,answers=(data.choice_answers||{}) as Answers,summary=alignmentSummary(answers);
 useEffect(()=>{setInterestInput(String((answers.interests as Answers[string]&{detail?:string}|undefined)?.detail||''));},[(answers.interests as Answers[string]&{detail?:string}|undefined)?.detail]);
 useEffect(()=>{if(phase==='questions'&&mode==='group'){questionNode.current?.scrollIntoView({block:'start'})}else if(stream.current)stream.current.scrollTop=0},[phase,step,mode]);
 const [discoveryChoice,setDiscoveryChoice]=useState<boolean|null>(null);
 const autoDiscovery=discoveryChoice??(typeof data.choice_auto_discovery==='boolean'?data.choice_auto_discovery:answers.initiative?.option!=='on_request');
 const answered=Object.keys(answers).length;
 const firstTask=snapshot.objects.task.find(t=>t.id===(data.choice_task_ref||data.first_value_ref));
 const selectedTask=firstValueChoices.find(t=>t.id===taskChoice)!;
 const taskContext=summary.filter(item=>selectedTask.questions.includes(item.question_id));
 const command=async(action:string,input:Record<string,unknown>={})=>{if(lock.current)return;lock.current=true;setBusy(true);try{return await runtime.command(action,{id:session.id,version:session.version,...input})}finally{lock.current=false;setBusy(false)}};
 const act=(action:string,input:Record<string,unknown>={})=>void command(action,input).catch(()=>{});
 const defer=()=>void command('onboarding.choice.defer').then(result=>{if(result)onExit()}).catch(()=>{});
 const home=()=>void command('onboarding.choice.home').then(result=>{if(result)onExit()}).catch(()=>{});
 const first=()=>void command('onboarding.choice.first',{task:taskChoice,confirm:true}).catch(()=>{});
 const groupTurns=(data.turns||[]) as {role:string;text?:string;participant?:string;task_id?:string}[];
 const groupPending=groupTurns.some(turn=>{const task=snapshot.objects.task.find(item=>item.id===turn.task_id);return task&&['queued','running','cancel_requested','pause_requested'].includes(String(task.data.status));});
 const sendGroup=async(event:FormEvent)=>{event.preventDefault();const content=groupInput.trim();if(!content||busy||groupPending)return;try{await command('onboarding.chat.reply',{text:content,model_consent:true});setGroupInput('');}catch{}};
 const groupDialogue=()=>mode==='group'&&<section className="elfred-choice-group-chat" aria-label="Agent 群聊对齐">{groupTurns.filter(turn=>turn.role==='user'||turn.role==='assistant').map((turn,index)=>{const task=snapshot.objects.task.find(item=>item.id===turn.task_id),run=snapshot.objects.run.find(item=>item.id===task?.data.run_id),answer=finalReceipts((run?.data.receipts||[]) as {phase?:string;output?:unknown;provider?:string}[]).find(item=>typeof item.output==='string')?.output;return <div key={index} className={'elfred-choice-chat-turn '+(turn.role==='user'?'mine':'agent')}><b>{turn.role==='user'?'我':nameOf(turn.participant||'owner')+' Agent'}</b>{typeof answer==='string'?<MarkdownContent text={answer}/>:<p>{turn.role==='user'?turn.text:task&&['blocked','failed'].includes(String(task.data.status))?'回复失败，可继续选择或稍后重试':'正在回复…'}</p>}</div>})}<form onSubmit={sendGroup}><input aria-label="向 Agent 群聊补充说明" value={groupInput} maxLength={2000} placeholder="补充你的想法，或直接选择上方答案" onChange={event=>setGroupInput(event.target.value)}/><button type="submit" disabled={busy||groupPending||!groupInput.trim()}>发送</button></form><small>本轮内容只在初始化会话共享；不会自动进入长期记忆。选项仍需你亲自确认。</small></section>;
 const optionsCard=(index:number)=>{const q=alignmentQuestions[index];return <section ref={questionNode} className="elfred-choice-question" key={q.id} aria-label={q.title}><div className="elfred-choice-speaker"><span>{nameOf(q.agent)}{mode==='group'?' · 在群聊中提问':''}</span><small>{index+1} / {alignmentQuestions.length}</small></div><h2>{displayTitle(q.title,'')}</h2>{q.id==='interests'&&<label className="elfred-interest-field">你想关注的具体领域（可写多个）<input aria-label="感兴趣的领域" maxLength={120} value={interestInput} placeholder="例如：AI 产品、城市生活、摄影" onChange={event=>setInterestInput(event.target.value)}/><small>只作为探索 Agent 的初始线索，不代表永久偏好。</small></label>}<div className="elfred-choice-options">{q.options.map(option=><button type="button" key={option.id} aria-pressed={answers[q.id]?.option===option.id} disabled={busy||q.id==='interests'&&option.id==='specified'&&interestInput.trim().length<2} className={['none','unsure','skip'].includes(option.id)?'is-optional':''} onClick={()=>act('onboarding.choice.answer',{question_id:q.id,option:option.id,...(q.id==='interests'&&option.id==='specified'?{detail:interestInput.trim()}: {})})}><span>{option.label}</span>{answers[q.id]?.option===option.id?<CheckCircle2 size={18}/>:<ChevronRight size={16}/>}</button>)}</div><small>{q.agent==='owner'?'Person Agent 保留当前需要和边界，按任务分配必要摘要。':`这项选择归${nameOf(q.agent)}，其他 Agent 不因此获得其私有记忆。`}</small></section>};
 return <main className="elfred-onboarding-chat elfred-choice-onboarding">
  <header><button type="button" aria-label="保存并返回首页" disabled={busy} onClick={defer}><ArrowLeft size={20}/></button><span>认识你的 Elfred<small>选择几项，从一件小事开始</small></span><button type="button" disabled={busy} onClick={defer}>稍后继续</button></header>
  <section ref={stream} className="elfred-onboarding-stream">
   <div className="elfred-onboarding-modes" aria-label="对齐组织方式">{[['sequential','逐个 Agent 对齐'],['group','Agent 群聊对齐']].map(([value,label])=><button type="button" key={value} aria-pressed={mode===value} disabled={busy} onClick={()=>act('onboarding.choice.mode',{mode:value})}>{label}</button>)}</div>
   {phase==='intro'?<><div className="elfred-onboarding-welcome"><Sparkles size={28}/><h1>先认识，再一起开始</h1><p>Elfred 是你的个人助手。Person Agent 负责理解你的需要、安排协作，五个 Agent 各有分工。你只需选择，不用介绍自己或写提示词。</p></div><section className="elfred-onboarding-team"><div className="elfred-onboarding-roles">{onboardingGuides.map((guide,index)=>{const Icon=icons[index];return <div key={guide.id}><Icon size={20}/><span><b>{guide.name}</b><small>{guide.duty}</small></span></div>})}</div><p>选择只形成初步理解，你可以随时修改或保留“不确定”。各 Agent 的私库保持隔离；联系他人、公开发布和高风险操作必须另行确认。</p><p>日历、文件和消息在任务真正需要时才申请使用。</p></section><section className="elfred-choice-question"><small>这次从一个具体场景开始</small><h2>想做一个轻量项目，但还没想好怎么开始</h2><p>不需要现在确定项目内容。我们用相同的几个选择，了解你希望怎样获得帮助。</p><button className="v277-primary" disabled={busy} onClick={()=>act('onboarding.choice.start',{mode})}>从这个场景开始</button><button className="v277-secondary" disabled={busy} onClick={defer}>暂时没有目标，先看看首页</button></section>{(data.turns as unknown[]|undefined)?.length?<details className="elfred-onboarding-team"><summary>此前的对话进度已保留</summary><p>新的初始化采用选择式；此前的任务和输入不会被清空。</p>{firstTask&&<button type="button" onClick={()=>go({name:'task',id:firstTask.id})}>继续已有任务</button>}</details>:null}</>:<>
    <div className="elfred-choice-context"><small>共同场景</small><b>开始一个轻量项目</b><span>{answered} / {alignmentQuestions.length} 项已选择 · 自动保存</span></div>
    <p className="elfred-choice-note">{mode==='sequential'?'每次和一位 Agent 对齐，再由 Person Agent 汇总。':'五个 Agent 在同一会话中分工提问，Person Agent 控制节奏并汇总。'}切换会保留全部选择。</p>
    {phase==='questions'&&<>{mode==='group'&&<><div className="elfred-choice-team-line">{onboardingGuides.map(g=><span key={g.id}>{g.name}</span>)}</div>{alignmentQuestions.slice(0,step).map((q,index)=><div className="elfred-group-turn" key={q.id}><p><b>{nameOf(q.agent)} Agent</b> {q.title}</p><button type="button" disabled={busy} onClick={()=>act('onboarding.choice.step',{step:index})}>{summary[index].label} · 修改</button></div>)}</>}{optionsCard(Math.min(step,alignmentQuestions.length-1))}{groupDialogue()}<div className="elfred-choice-navigation"><button type="button" disabled={busy||step===0} onClick={()=>act('onboarding.choice.step',{step:step-1})}>上一项</button><button type="button" disabled={busy} onClick={()=>act('onboarding.choice.step',{step:alignmentQuestions.length})}>先核对已选内容</button></div></>}
    {phase==='summary'&&<section className="elfred-onboarding-review"><small>Person Agent 为你汇总</small><h2>初始理解卡</h2><p>以下是本次选择形成的初始假设，不是永久标签。未确认的内容会保持未知。</p>{summary.map((item,index)=><div className="elfred-choice-summary-row" key={item.question_id}><div><small>{nameOf(item.agent)} · {item.question}</small><b>{item.label}</b><small>{item.certainty==='uncertain'?'理解不足 · 后续按需补充':'本人选择 · 仍需在真实场景中验证'}</small></div><button type="button" aria-label={`修改：${item.question}`} disabled={busy} onClick={()=>act('onboarding.choice.step',{step:index})}>修改</button></div>)}<details className="elfred-onboarding-team"><summary>哪些信息由谁使用</summary>{onboardingGuides.map(g=><p key={g.id}><b>{g.name}：</b>{summary.filter(item=>item.agent===g.id).map(item=>item.label).join('、')}。{summary.some(item=>item.agent===g.id&&item.certainty==='selected')?'只形成当前方向，不提升为稳定理解。':'尚不了解，使用时再补充。'}</p>)}<p>Person Agent 保留你的当前需要、主动程度和对外边界；创建任务时，你可以核对交给负责 Agent 的最小摘要。组织方式不会改变私库权限。</p></details><p>你可以把任一项改为“都不符合”或“不确定”，它将退出有效理解；原选择的历史版本保留以供追溯。</p><p>主动程度是服务偏好，不是执行授权。对外联系、发布、改动安排及高风险操作仍须在实际任务中确认；未连接的信息源不会被读取。</p><label className="elfred-discovery-choice"><input type="checkbox" checked={autoDiscovery} disabled={busy} onChange={event=>setDiscoveryChoice(event.target.checked)}/>按这些选择自动发现公开资讯</label><small>每日筛选公开资讯并更新私人朋友圈，不联系他人或发布到社区；可随时暂停。没有匹配内容时保持空态。</small>{phase==='summary'&&<><button className="v277-primary" disabled={busy} onClick={()=>act('onboarding.choice.confirm',{confirm:true,auto_discovery:autoDiscovery})}>确认这些选择</button><button type="button" disabled={busy} onClick={()=>act('onboarding.choice.confirm',{confirm:true,auto_discovery:autoDiscovery})}>暂时按这样开始</button></>}</section>}
    {phase==='handoff'&&<section className="elfred-onboarding-review"><small>初始理解已保存，仍可随时调整</small><button type="button" disabled={busy} onClick={()=>act('onboarding.choice.step',{step:alignmentQuestions.length})}>查看或修改初始理解卡</button><h2>{data.choice_task_ref?'首个待处理事项已保存':'选择第一件小事'}</h2>{data.choice_task_ref&&firstTask?<><p>{text(session,'choice_task_label')} · {statuses[text(firstTask,'status')]||text(firstTask,'status')}</p><p>{firstTask.data.status==='completed'?'打开任务查看成果与验收记录。':'已存入收件箱，执行前仍需确认。任务尚未完成时，不会显示为已有成果。'}</p>{JSON.stringify(data.choice_task_answers)!==JSON.stringify(answers)&&<p>理解卡已修改；已有任务保留创建时的选择。打开任务核对后再执行。</p>}<button className="v277-primary" onClick={()=>go({name:'task',id:firstTask.id})}>查看首个任务与成果</button><button type="button" onClick={()=>go({name:'inbox'})}>查看收件箱</button></>:<><p>继续选择就能开始，不必填写任务内容。</p><div className="elfred-choice-options">{firstValueChoices.map(option=><button type="button" aria-pressed={taskChoice===option.id} key={option.id} onClick={()=>setTaskChoice(option.id)}>{option.label}{taskChoice===option.id&&<CheckCircle2 size={18}/>}</button>)}</div><details className="elfred-onboarding-team" open><summary>本次交给{nameOf(selectedTask.system)}的内容</summary>{taskContext.map(item=><p key={item.question_id}>{item.question} {item.label}</p>)}<small>只用于这次任务，未选择的具体领域、个人经历和日程仍为未知。</small></details><button className="v277-primary" disabled={busy} onClick={first}>确认并存入收件箱</button></>}<p>先使用现有能力，不强制安装或保存 Skill。需要资料时再授权。</p><button type="button" onClick={()=>go({name:'my-tools'})}>查看我的工具</button><button className="v277-primary" disabled={busy} onClick={home}>{data.choice_task_ref?'进入首页，继续推进':'先看看首页'}</button></section>}
   </>}
  </section>
 </main>;
}
