"use client";
import {displayTitle} from "../../core/display-labels";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {ArrowLeft,Sparkles,Compass,Lightbulb,PenLine,Link2,CheckCircle2,ChevronRight} from 'lucide-react';
import {useRuntime} from '../../core/runtime-context';
import {onboardingGuides} from '../../core/onboarding-guides.mjs';
import {alignmentQuestions,alignmentSummary,firstValueChoices,interestLabels,interestOptions} from '../../core/onboarding-choice.mjs';
import {text,statuses} from '../live/types';
import {finalReceipts} from '../../core/result-output';
import {MarkdownContent} from '../../core/markdown-content';
import {VoiceInput} from '../messages/voice-input';
import type {Screen} from '../../core/screen';
import './onboarding-conversation.css';
import './onboarding-v2.css';

const icons=[Compass,Lightbulb,PenLine,Link2,CheckCircle2];
const teamDirections:Record<string,string[]>={
 explore:['关注领域的新信息','寻找相邻机会','追踪指定来源','发现不同观点'],
 advise:['比较方案与风险','检查决策依据','提醒关键取舍','复盘反复出现的问题'],
 create:['制作产品方案','撰写内容草稿','整理表达风格','修改已有作品'],
 connect:['寻找合适的人','准备沟通草稿','关注合作机会','维护已有关系'],
 execute:['拆解第一步','推进待办任务','检查交付结果','提醒待确认事项']
};
const nameOf=(id:string)=>id==='owner'?'Person Agent':onboardingGuides.find(g=>g.id===id)?.name||id;
type Answers=Record<string,{option:string;at:string;scope:string;detail?:string;tags?:string[]}>;
function goalSuggestion(output:unknown){
 if(typeof output!=='string')return null;
 try{const source=output.replace(/^```(?:json)?\s*|\s*```$/g,'').trim();const start=source.indexOf('{'),end=source.lastIndexOf('}');if(start<0||end<=start)return null;const parsed=JSON.parse(source.slice(start,end+1));const tasks=Array.isArray(parsed.first_tasks)?parsed.first_tasks.slice(0,3).map((row:Record<string,unknown>,index:number)=>({id:`suggestion:${index}`,label:String(row.label||'').slice(0,80),goal:String(row.goal||'').slice(0,500),system:String(row.system||''),minutes:Number(row.minutes)||10,needs:String(row.needs||'').slice(0,150),deliverable:String(row.deliverable||'').slice(0,150)})).filter((row:{label:string;goal:string;system:string})=>row.label&&row.goal&&['explore','advise','create','connect','execute'].includes(row.system)):[];return {goal:String(parsed.goal||'').slice(0,1000),result:String(parsed.result||'').slice(0,1000),criteria:String(parsed.criteria||'').slice(0,1000),days:[7,14,30].includes(Number(parsed.days))?Number(parsed.days):14,tasks:tasks.length===3?tasks:[]}}catch{return null}
}
export function OnboardingConversation({go,onExit}:{go:(screen:Screen)=>void;onExit:()=>void}){
 const runtime=useRuntime()!,snapshot=runtime.snapshot!,session=snapshot.objects.onboarding[0];
 const [busy,setBusy]=useState(false),[taskChoice,setTaskChoice]=useState('outline'),[interestTags,setInterestTags]=useState<string[]>([]),[interestInput,setInterestInput]=useState(''),[groupInput,setGroupInput]=useState(''),lock=useRef(false),stream=useRef<HTMLElement>(null),questionNode=useRef<HTMLElement>(null);
 const data=session.data,mode=text(session,'choice_mode')||'sequential',phase=text(session,'choice_phase')||'intro';
 const savedProfile=data.choice_profile as {name?:string;role?:string;status?:string;interests?:string[]}|undefined;
 const savedGoal=data.choice_goal as {goal?:string;result?:string;criteria?:string;days?:number}|undefined;
 const [profileName,setProfileName]=useState(savedProfile?.name||snapshot.user.name||''),[profileRole,setProfileRole]=useState(savedProfile?.role||''),[profileStatus,setProfileStatus]=useState(savedProfile?.status||'');
 const [goal,setGoal]=useState(savedGoal?.goal||''),[goalResult,setGoalResult]=useState(savedGoal?.result||''),[goalCriteria,setGoalCriteria]=useState(savedGoal?.criteria||''),[goalDays,setGoalDays]=useState(savedGoal?.days||14);
 const goalProposalTask=snapshot.objects.task.find(item=>item.id===data.choice_goal_proposal_task_ref);
 const goalProposalRun=snapshot.objects.run.find(item=>item.id===goalProposalTask?.data.run_id);
 const goalProposal=goalSuggestion(finalReceipts((goalProposalRun?.data.receipts||[]) as {phase?:string;output?:unknown;provider?:string}[]).find(item=>typeof item.output==='string')?.output);
 const [agentFocus,setAgentFocus]=useState<Record<string,string>>(()=>({explore:'关注所选领域的新信息和机会',advise:'比较近期目标的方案与风险',create:'围绕近期目标产出可修改的作品',connect:'寻找与目标有关的人和合作可能',execute:'拆解第一步并推进交付',...(data.choice_agent_focus||{})}));
 const step=Number(data.choice_step)||0,answers=(data.choice_answers||{}) as Answers,summary=alignmentSummary(answers);
 const savedInterest=answers.interests?.tags?.join('、')||answers.interests?.detail||'';
 useEffect(()=>{setInterestTags(interestLabels(savedInterest));setInterestInput('');},[savedInterest]);
 useEffect(()=>{if(phase==='questions'&&mode==='group'){questionNode.current?.scrollIntoView({block:'start'})}else if(stream.current)stream.current.scrollTop=0},[phase,step,mode]);
 const [discoveryChoice,setDiscoveryChoice]=useState<boolean|null>(null);
 const autoDiscovery=discoveryChoice??(typeof data.choice_auto_discovery==='boolean'?data.choice_auto_discovery:answers.initiative?.option!=='on_request');
 const [peerChoice,setPeerChoice]=useState<boolean|null>(null);
 const autoPeerComments=peerChoice??(data.choice_auto_peer_comments===true||phase==='team');
 const answered=Object.keys(answers).length;
 const firstTask=snapshot.objects.task.find(t=>t.id===(data.choice_task_ref||data.first_value_ref));
 const taskOptions=savedGoal&&data.choice_goal_proposal_input===savedGoal.goal&&goalProposal?.tasks.length===3?goalProposal.tasks:firstValueChoices;
 const selectedTask=taskOptions.find((t:{id:string})=>t.id===taskChoice)||taskOptions[0];
 const taskContext=(savedGoal?(data.choice_summary||[]) as typeof summary:summary).filter(item=>('questions' in selectedTask&&Array.isArray(selectedTask.questions)&&selectedTask.questions.includes(item.question_id))||Boolean(savedGoal&&item.question_id==='need'));
 const command=async(action:string,input:Record<string,unknown>={})=>{if(lock.current)return;lock.current=true;setBusy(true);try{return await runtime.command(action,{id:session.id,version:session.version,...input})}finally{lock.current=false;setBusy(false)}};
 const act=(action:string,input:Record<string,unknown>={})=>void command(action,input).catch(()=>{});
 const defer=()=>void command('onboarding.choice.defer').then(result=>{if(result)onExit()}).catch(()=>{});
 const home=()=>void command('onboarding.choice.home').then(result=>{if(result)onExit()}).catch(()=>{});
 const first=()=>void command('onboarding.choice.first',{task:selectedTask.id,confirm:true,...(savedGoal?{start:true,model_consent:true}:{})}).catch(()=>{});
 const groupTurns=(data.turns||[]) as {role:string;text?:string;participant?:string;task_id?:string}[];
 const groupPending=groupTurns.some(turn=>{const task=snapshot.objects.task.find(item=>item.id===turn.task_id);return task&&['queued','running','cancel_requested','pause_requested'].includes(String(task.data.status));});
 const sendGroup=async(event:FormEvent)=>{event.preventDefault();const content=groupInput.trim();if(!content||busy||groupPending)return;try{await command('onboarding.chat.reply',{text:content,model_consent:true});setGroupInput('');}catch{}};
 const groupDialogue=()=>mode==='group'&&<section className="elfred-choice-group-chat" aria-label="Agent 群聊对齐">{groupTurns.filter(turn=>turn.role==='user'||turn.role==='assistant').map((turn,index)=>{const task=snapshot.objects.task.find(item=>item.id===turn.task_id),run=snapshot.objects.run.find(item=>item.id===task?.data.run_id),answer=finalReceipts((run?.data.receipts||[]) as {phase?:string;output?:unknown;provider?:string}[]).find(item=>typeof item.output==='string')?.output;return <div key={index} className={'elfred-choice-chat-turn '+(turn.role==='user'?'mine':'agent')}><b>{turn.role==='user'?'我':nameOf(turn.participant||'owner')+' Agent'}</b>{typeof answer==='string'?<MarkdownContent text={answer}/>:<p>{turn.role==='user'?turn.text:task&&['blocked','failed'].includes(String(task.data.status))?'回复失败，可继续选择或稍后重试':'正在回复…'}</p>}</div>})}<form onSubmit={sendGroup}><input aria-label="向 Agent 群聊补充说明" value={groupInput} maxLength={2000} placeholder="补充你的想法，或直接选择上方答案" onChange={event=>setGroupInput(event.target.value)}/><button type="submit" disabled={busy||groupPending||!groupInput.trim()}>发送</button></form><small>本轮内容只在初始化会话共享；不会自动进入长期记忆。选项仍需你亲自确认。</small></section>;
 const optionsCard=(index:number)=>{
  const q=alignmentQuestions[index];
  const selectedInterests=interestLabels([...interestTags,...interestLabels(interestInput)]);
  const interestDetail=selectedInterests.join('、');
  const interestValid=selectedInterests.length>0&&selectedInterests.length<=8&&interestDetail.length<=120&&selectedInterests.every(tag=>tag.length>=2&&tag.length<=30&&!/[<>]/.test(tag));
  return <section ref={questionNode} className="elfred-choice-question" key={q.id} aria-label={q.title}>
   <div className="elfred-choice-speaker"><span>{nameOf(q.agent)}{mode==='group'?' · 在群聊中提问':''}</span><small>{index+1} / {alignmentQuestions.length}</small></div>
   <h2>{displayTitle(q.title,'')}</h2>
   {q.id==='interests'&&<div className="elfred-interest-selector">
    <small>可以多选，最多 8 个。只作为探索 Agent 的初始线索，之后可以修改。</small>
    <div className="elfred-interest-tags">{[...interestOptions,...interestTags.filter(tag=>!interestOptions.includes(tag))].map(tag=>{
     const picked=interestTags.includes(tag);
     return <button key={tag} type="button" aria-pressed={picked} disabled={busy||(!picked&&selectedInterests.length>=8)} onClick={()=>setInterestTags(current=>picked?current.filter(item=>item!==tag):[...current,tag])}>{tag}{picked&&<CheckCircle2 size={14}/>}</button>;
    })}</div>
    <label className="elfred-interest-field">没有合适的？可以补充<input aria-label="补充感兴趣的领域" maxLength={120} value={interestInput} placeholder="输入领域，多个用逗号分开" onChange={event=>setInterestInput(event.target.value)}/></label>
    <small>已选 {selectedInterests.length} / 8</small>
    <button className="elfred-interest-confirm" type="button" disabled={busy||!interestValid} onClick={()=>act('onboarding.choice.answer',{question_id:q.id,option:'specified',tags:selectedInterests})}>确认已选领域</button>
   </div>}
   <div className="elfred-choice-options">{q.options.filter(option=>q.id!=='interests'||option.id!=='specified').map(option=><button type="button" key={option.id} aria-pressed={answers[q.id]?.option===option.id} disabled={busy} className={['none','unsure','skip'].includes(option.id)?'is-optional':''} onClick={()=>act('onboarding.choice.answer',{question_id:q.id,option:option.id})}><span>{option.label}</span>{answers[q.id]?.option===option.id?<CheckCircle2 size={18}/>:<ChevronRight size={16}/>}</button>)}</div>
   <small>{q.agent==='owner'?'Person Agent 保留当前需要和边界，按任务分配必要摘要。':`这项选择归${nameOf(q.agent)}，其他 Agent 不因此获得其私有记忆。`}</small>
  </section>;
 };
 return <main className="elfred-onboarding-chat elfred-choice-onboarding">
  <header><button type="button" aria-label="保存并返回首页" disabled={busy} onClick={defer}><ArrowLeft size={20}/></button><span>认识你的 Elfred<small>选择几项，从一件小事开始</small></span><button type="button" disabled={busy} onClick={defer}>稍后继续</button></header>
  <section ref={stream} className="elfred-onboarding-stream">
   {['questions','summary'].includes(phase)&&<div className="elfred-onboarding-modes" aria-label="对齐组织方式">{[['sequential','逐个 Agent 对齐'],['group','Agent 群聊对齐']].map(([value,label])=><button type="button" key={value} aria-pressed={mode===value} disabled={busy} onClick={()=>act('onboarding.choice.mode',{mode:value})}>{label}</button>)}</div>}
   {phase==='intro'?<><div className="elfred-onboarding-welcome"><Sparkles size={28}/><h1>建立一个会越来越懂你的 Elfred</h1><p>它会记住你的目标与方法，并调动 5 个 Agent 帮你推进事情。</p></div><section className="elfred-onboarding-team elfred-v2-value-cards"><div><b>理解你</b><p>你能核对和修改它记住的内容。</p></div><div><b>帮助你</b><p>五个 Agent 各司其职，交付有来源的结果。</p></div><div><b>与你成长</b><p>真实成果和反馈推动能力成长。</p></div></section><section className="elfred-choice-question"><button className="v277-primary" disabled={busy} onClick={()=>act('onboarding.choice.profile.start')}>开始建立我的 Elfred</button><button type="button" disabled={busy} onClick={()=>act('onboarding.choice.start',{mode})}>按原有方式逐项对齐</button></section></>:<>
    {phase==='profile'&&<section className="elfred-choice-question elfred-v2-form"><small>1 / 4 · 基础信息</small><h2>先告诉 Elfred 怎么称呼你</h2><label>称呼<input value={profileName} maxLength={60} onChange={event=>setProfileName(event.target.value)} placeholder="希望 Elfred 怎么称呼你"/></label><p>当前角色</p><div className="elfred-interest-tags">{['创业者','学生','产品','设计','开发','内容','市场','自由职业'].map(value=><button key={value} type="button" aria-pressed={profileRole===value} onClick={()=>setProfileRole(value)}>{value}</button>)}</div><input value={profileRole} maxLength={60} aria-label="自定义当前角色" onChange={event=>setProfileRole(event.target.value)} placeholder="也可以输入其他角色"/><p>感兴趣的领域（可多选）</p><div className="elfred-interest-tags">{interestOptions.map(value=><button key={value} type="button" aria-pressed={interestTags.includes(value)} onClick={()=>setInterestTags(current=>current.includes(value)?current.filter(item=>item!==value):current.length<8?[...current,value]:current)}>{value}</button>)}</div><input value={interestInput} maxLength={120} aria-label="补充感兴趣领域" onChange={event=>setInterestInput(event.target.value)} placeholder="没有合适的？补充领域，用逗号分开"/><p>当前状态</p><div className="elfred-interest-tags">{['正在工作','找工作','创业中','学习中','寻找方向'].map(value=><button key={value} type="button" aria-pressed={profileStatus===value} onClick={()=>setProfileStatus(value)}>{value}</button>)}</div><button className="v277-primary" disabled={busy||!profileName.trim()||!profileRole.trim()||!profileStatus.trim()||!interestLabels([...interestTags,...interestLabels(interestInput)]).length} onClick={()=>act('onboarding.choice.profile',{name:profileName,role:profileRole,status:profileStatus,interests:interestLabels([...interestTags,...interestLabels(interestInput)])})}>继续</button></section>}
    {phase==='goal'&&<section className="elfred-choice-question elfred-v2-form"><small>2 / 4 · 近期目标</small><h2>未来 7～30 天，你最想推进什么？</h2><textarea value={goal} maxLength={1000} onChange={event=>setGoal(event.target.value)} placeholder="例如：完成产品 Demo、找到工作、建立稳定内容流程"/><div className="elfred-v2-goal-actions"><VoiceInput onText={value=>setGoal(current=>(current+" "+value).trim().slice(0,1000))} disabled={busy}/><button type="button" className="v277-secondary" disabled={busy||!goal.trim()||["queued","running"].includes(String(goalProposalTask?.data.status))} onClick={()=>act("onboarding.choice.goal.organize",{goal,confirm:true,model_consent:true})}>让 Elfred 整理目标</button></div>{goalProposalTask&&["queued","running"].includes(String(goalProposalTask.data.status))&&<p role="status">Elfred 正在整理目标，完成后可选择采用建议。</p>}{goalProposal&&<div className="elfred-onboarding-team"><b>Elfred 的整理建议 · 可修改</b><p>{goalProposal.goal||"目标待你补充"}</p><small>{goalProposal.result||"结果待你补充"} · {goalProposal.days} 天 · {goalProposal.criteria||"完成标准待你补充"}</small><button type="button" className="v277-secondary" onClick={()=>{if(goalProposal.goal)setGoal(goalProposal.goal);if(goalProposal.result)setGoalResult(goalProposal.result);if(goalProposal.criteria)setGoalCriteria(goalProposal.criteria);setGoalDays(goalProposal.days)}}>采用并继续修改</button></div>}{goalProposalTask&&["blocked","failed"].includes(String(goalProposalTask.data.status))&&<p role="alert">整理暂时未完成；你仍可自己填写目标。</p>}<label>希望完成的结果<input value={goalResult} maxLength={1000} onChange={event=>setGoalResult(event.target.value)} placeholder="最终想看到什么"/></label><label>判断完成的标准<input value={goalCriteria} maxLength={1000} onChange={event=>setGoalCriteria(event.target.value)} placeholder="怎样才算完成"/></label><label>预计时间<select value={goalDays} onChange={event=>setGoalDays(Number(event.target.value))}><option value={7}>7 天</option><option value={14}>14 天</option><option value={30}>30 天</option></select></label><div className="elfred-onboarding-team"><b>目标整理卡 · 可直接修改</b><p>{goal||'你填写的目标会显示在这里'}</p><small>{goalResult||'希望完成的结果'} · {goalDays} 天 · {goalCriteria||'完成标准待填写'}</small></div><button className="v277-primary" disabled={busy||!goal.trim()||!goalResult.trim()||!goalCriteria.trim()} onClick={()=>act('onboarding.choice.goal',{goal,result:goalResult,criteria:goalCriteria,days:goalDays})}>确认这个目标</button></section>}
    {phase==='team'&&<section className="elfred-choice-question elfred-v2-form"><small>3 / 4 · AI 团队</small><h2>这是你的五个 Agent</h2><p>每位 Agent 可选一个当前方向，也可以修改重点。</p>{onboardingGuides.map(guide=><div className="elfred-v2-agent-direction" key={guide.id}><b>{guide.name} · {guide.duty}</b><div className="elfred-interest-tags">{teamDirections[guide.id].map(direction=><button type="button" key={direction} aria-pressed={agentFocus[guide.id]===direction} onClick={()=>setAgentFocus(current=>({...current,[guide.id]:direction}))}>{direction}</button>)}</div><label>当前重点<input value={agentFocus[guide.id]||''} maxLength={200} onChange={event=>setAgentFocus(current=>({...current,[guide.id]:event.target.value}))}/></label></div>)}<label className="elfred-discovery-choice"><input type="checkbox" checked={autoDiscovery} onChange={event=>setDiscoveryChoice(event.target.checked)}/>按所选领域订阅公开资讯并在私人朋友圈更新</label><label className="elfred-discovery-choice"><input type="checkbox" checked={autoPeerComments} onChange={event=>setPeerChoice(event.target.checked)}/>让其他 Agent 在有增量价值时补充评论（每日最多 3 次模型调用）</label><button className="v277-primary" disabled={busy||onboardingGuides.some(guide=>!agentFocus[guide.id]?.trim())} onClick={()=>act('onboarding.choice.team',{focus:agentFocus,auto_discovery:autoDiscovery,auto_peer_comments:autoPeerComments,model_consent:autoPeerComments,confirm:true})}>确认五个 Agent 的方向</button></section>}
    {['questions','summary'].includes(phase)&&<><div className="elfred-choice-context"><small>共同场景</small><b>开始一个轻量项目</b><span>{answered} / {alignmentQuestions.length} 项已选择 · 自动保存</span></div><p className="elfred-choice-note">{mode==='sequential'?'每次和一位 Agent 对齐，再由 Person Agent 汇总。':'五个 Agent 在同一会话中分工提问，Person Agent 控制节奏并汇总。'}切换会保留全部选择。</p></>}
    {phase==='questions'&&<>{mode==='group'&&<><div className="elfred-choice-team-line">{onboardingGuides.map(g=><span key={g.id}>{g.name}</span>)}</div>{alignmentQuestions.slice(0,step).map((q,index)=><div className="elfred-group-turn" key={q.id}><p><b>{nameOf(q.agent)} Agent</b> {q.title}</p><button type="button" disabled={busy} onClick={()=>act('onboarding.choice.step',{step:index})}>{summary[index].label} · 修改</button></div>)}</>}{optionsCard(Math.min(step,alignmentQuestions.length-1))}{groupDialogue()}<div className="elfred-choice-navigation"><button type="button" disabled={busy||step===0} onClick={()=>act('onboarding.choice.step',{step:step-1})}>上一项</button><button type="button" disabled={busy} onClick={()=>act('onboarding.choice.step',{step:alignmentQuestions.length})}>先核对已选内容</button></div></>}
    {phase==='summary'&&<section className="elfred-onboarding-review"><small>Person Agent 为你汇总</small><h2>初始理解卡</h2><p>以下是本次选择形成的初始假设，不是永久标签。未确认的内容会保持未知。</p>{summary.map((item,index)=><div className="elfred-choice-summary-row" key={item.question_id}><div><small>{nameOf(item.agent)} · {item.question}</small><b>{item.label}</b><small>{item.certainty==='uncertain'?'理解不足 · 后续按需补充':'本人选择 · 仍需在真实场景中验证'}</small></div><button type="button" aria-label={`修改：${item.question}`} disabled={busy} onClick={()=>act('onboarding.choice.step',{step:index})}>修改</button></div>)}<details className="elfred-onboarding-team"><summary>哪些信息由谁使用</summary>{onboardingGuides.map(g=><p key={g.id}><b>{g.name}：</b>{summary.filter(item=>item.agent===g.id).map(item=>item.label).join('、')}。{summary.some(item=>item.agent===g.id&&item.certainty==='selected')?'只形成当前方向，不提升为稳定理解。':'尚不了解，使用时再补充。'}</p>)}<p>Person Agent 保留你的当前需要、主动程度和对外边界；创建任务时，你可以核对交给负责 Agent 的最小摘要。组织方式不会改变私库权限。</p></details><p>你可以把任一项改为“都不符合”或“不确定”，它将退出有效理解；原选择的历史版本保留以供追溯。</p><p>主动程度是服务偏好，不是执行授权。对外联系、发布、改动安排及高风险操作仍须在实际任务中确认；未连接的信息源不会被读取。</p><label className="elfred-discovery-choice"><input type="checkbox" checked={autoDiscovery} disabled={busy} onChange={event=>setDiscoveryChoice(event.target.checked)}/>按这些选择自动发现公开资讯</label><small>每日筛选公开资讯并更新私人朋友圈，不联系他人或发布到社区；可随时暂停。没有匹配内容时保持空态。</small><label className="elfred-discovery-choice"><input type="checkbox" checked={autoPeerComments} disabled={busy} onChange={event=>setPeerChoice(event.target.checked)}/>允许其他 Agent 对真实动态自主评论</label><small>评论仅在你的私人朋友圈展示；每天最多 3 次模型调用，每次最多 1000 本地额度。可在朋友圈筛选中暂停。</small>{phase==='summary'&&<><button className="v277-primary" disabled={busy} onClick={()=>act('onboarding.choice.confirm',{confirm:true,auto_discovery:autoDiscovery,auto_peer_comments:autoPeerComments,model_consent:autoPeerComments})}>确认这些选择</button><button type="button" disabled={busy} onClick={()=>act('onboarding.choice.confirm',{confirm:true,auto_discovery:autoDiscovery,auto_peer_comments:autoPeerComments,model_consent:autoPeerComments})}>暂时按这样开始</button></>}</section>}
    {phase==='handoff'&&<section className="elfred-onboarding-review"><small>{savedGoal?'4 / 4 · 首个任务 · 当前 L2':'初始理解已保存'}</small>{!savedGoal&&<button type="button" disabled={busy} onClick={()=>act('onboarding.choice.step',{step:alignmentQuestions.length})}>查看或修改初始理解卡</button>}<h2>{data.choice_task_ref?'你的 Elfred 已经开始工作':'选择第一件小事'}</h2>{savedGoal&&<p>当前目标：{savedGoal.goal}。五个 Agent 已按你的方向建立。</p>}{data.choice_task_ref&&firstTask?<><p>{text(session,'choice_task_label')} · {statuses[text(firstTask,'status')]||text(firstTask,'status')}</p><p>{firstTask.data.status==='completed'?'打开任务查看成果与验收记录。':savedGoal?'首个任务正在推进；有结果后由你验收。':'已存入收件箱，执行前仍需确认。'}</p><button className="v277-primary" onClick={()=>go({name:'task',id:firstTask.id})}>查看首个任务</button></>:<><p>{savedGoal?'选一个起点，确认使用你的目标与已选方向后立即开始。':'继续选择就能开始，不必填写任务内容。'}</p><div className="elfred-choice-options">{taskOptions.map((option:{id:string;label:string;system:string;minutes?:number;deliverable?:string})=><button type="button" aria-pressed={selectedTask.id===option.id} key={option.id} onClick={()=>setTaskChoice(option.id)}><b>{option.label}</b><small>{nameOf(option.system)} Agent · 约 {"minutes" in option?option.minutes:"5～10"} 分钟 · {"deliverable" in option?option.deliverable:"交付可修改的建议"}</small>{selectedTask.id===option.id&&<CheckCircle2 size={18}/>}</button>)}</div><details className="elfred-onboarding-team" open><summary>本次交给{nameOf(selectedTask.system)}的内容</summary>{taskContext.map(item=><p key={item.question_id}>{item.question} {item.label}</p>)}<small>只使用你确认的目标与方向，不联系他人、不公开发布。运行会调用已配置的模型。</small></details><button className="v277-primary" disabled={busy} onClick={first}>{savedGoal?'确认资料范围并开始第一个任务':'确认并存入收件箱'}</button></>}<p>需要更多资料或对外操作时仍会另行征求同意。</p><button className="v277-primary" disabled={busy||Boolean(savedGoal&&!data.choice_task_ref)} onClick={home}>进入首页</button></section>}
   </>}
  </section>
 </main>;
}
