"use client";
import {displayTitle} from "../../core/display-labels";
import {useState} from 'react';
import {useRuntime,entityRef} from '../../core/runtime-context';
import {Action,Field} from '../../core/runtime-panels';
import {text,type Entity} from '../live/types';
import type {Screen} from '../../core/screen';
export function ArtifactPreview({item,autoOpen=false}:{item:Entity;autoOpen?:boolean}){
 const [open,setOpen]=useState(autoOpen),[interactive,setInteractive]=useState(false);
 return item.data.format==='web'?<><button type="button" className="v277-secondary" onClick={()=>setOpen(!open)}>{open?'收起作品预览':'查看作品预览'}</button>{open&&<><button type="button" className="v277-secondary" onClick={()=>setInteractive(value=>!value)}>{interactive?'停止交互':'运行交互'}</button><iframe key={interactive?'interactive':'static'} title="共创作品预览" sandbox={interactive?'allow-scripts':''} src={`/api/elfred/preview/${item.id}`} style={{display:'block',width:'100%',height:360,border:'1px solid #e5e7eb',borderRadius:12}}/></>}</>:null;
}
type Slot={id:string;title:string;criteria:string;capacity:number|null;filled?:number;terms_changed?:boolean;rules_version?:number;risk?:string;participation?:string;deadline?:string;status:string;depends_on:string[];auto_brief?:boolean};
export function ProjectSlots({project,post,go}:{project?:Entity;post?:Entity;go:(screen:Screen)=>void}){
 const runtime=useRuntime()!,snapshot=runtime.snapshot!,owner=project?.owner===snapshot.user.id;
 const [title,setTitle]=useState(''),[criteria,setCriteria]=useState(''),[capacity,setCapacity]=useState('1'),[deadline,setDeadline]=useState(''),[depends,setDepends]=useState<string[]>([]),[risk,setRisk]=useState('low'),[participation,setParticipation]=useState('open'),[editing,setEditing]=useState<Entity|null>(null);
 const slots:Slot[]=project?snapshot.objects.project_slot.filter(item=>item.space===project.id).map(item=>({id:item.id,...item.data,rules_version:item.version} as Slot)):(post?.data.slots||[]) as Slot[];
 const publicPost=post||snapshot.objects.post.find(item=>item.data.project_id===project?.id);
 const singleBrief=!owner&&slots.length===1&&slots[0].auto_brief;
 return <section className="v277-edit-card"><h3>{singleBrief?'参与共创':'共创任务'}</h3>{!slots.length&&<p>项目尚未拆分任务位，可先整体参与。</p>}{slots.map(slot=>{
  const entity=snapshot.objects.project_slot.find(item=>item.id===slot.id),claim=snapshot.objects.claim.find(item=>item.data.slot_id===slot.id&&item.owner===snapshot.user.id&&['accepted','pending','needs_reconfirmation','needs_application_confirmation'].includes(text(item,'status')));
  const filled=slot.filled??snapshot.objects.claim.filter(c=>c.data.slot_id===slot.id&&['accepted','needs_reconfirmation'].includes(text(c,'status'))).length,closed=slot.status!=='open'||Boolean(slot.terms_changed)||Boolean(slot.deadline&&Date.parse(slot.deadline)<=Date.parse(snapshot.server_time)),full=slot.capacity!==null&&filled>=slot.capacity,approval=publicPost?.data.participation==='application'||slot.capacity!==null||slot.risk==='high'||slot.participation==='application';
  const declined=snapshot.objects.claim.find(c=>c.data.slot_id===slot.id&&c.owner===snapshot.user.id&&c.data.status==='declined');
  const hasWorkCopy=Boolean(project&&snapshot.objects.copy.some(copy=>copy.owner===snapshot.user.id&&copy.data.project_id===project.id&&copy.data.slot_id===slot.id));
  return <article key={slot.id} style={{padding:'12px 0',borderBottom:'1px solid #eceff1'}}>{!singleBrief&&<><b>{displayTitle(slot.title,'')}</b><p>{slot.criteria}</p></>}<small>{slot.capacity===null?'不限人数':`${filled}/${slot.capacity} 人`} · {slot.status==='completed'?'已完成':slot.terms_changed?'约定更新中，待重新公开':closed?'已关闭或截止':full?'已满员':approval?'申请后确认':'可直接认领'}{slot.deadline?` · 截止 ${new Date(slot.deadline).toLocaleString('zh-CN')}`:''}</small>{slot.depends_on?.length>0&&<p>前置任务：{slot.depends_on.map(id=>slots.find(s=>s.id===id)?.title||'前置任务').join('、')}</p>}
   {declined&&<p>上次申请：{text(declined,'review_note')}</p>}{claim?<><p>{claim.data.status==='accepted'?'已加入项目':claim.data.status==='needs_reconfirmation'?'任务约定已变更，需重新确认':claim.data.status==='needs_application_confirmation'?'申请约定已变更，需重新核对':'申请待审核'}</p>{claim.data.status==='needs_reconfirmation'&&<><p>新验收：{slot.criteria}</p><Action disabled={Boolean(slot.terms_changed)} run={()=>runtime.command('claim.reconfirm',{...entityRef(claim),slot_version:slot.rules_version,confirm:true})}>已核对变更，继续承担</Action></>}{claim.data.status==='needs_application_confirmation'&&publicPost&&<Action disabled={closed||full} run={()=>runtime.command('project.claim',{post_id:publicPost.id,slot_id:slot.id,slot_version:slot.rules_version,confirm:true})}>已核对新约定，重新申请</Action>}{claim.data.status==='accepted'&&project&&(hasWorkCopy?<button type="button" className="v277-secondary" onClick={()=>document.getElementById('my-project-work')?.scrollIntoView({behavior:'smooth',block:'start'})}>进入我的工作</button>:<Action run={()=>runtime.command('copy.create',{project_id:project.id,slot_id:slot.id})}>准备我的工作区</Action>)}<details><summary>参与管理</summary><Action run={()=>runtime.command('claim.withdraw',entityRef(claim))}>退出这项任务</Action></details></>:!owner&&publicPost&&slot.status==='open'&&<Action disabled={closed||full} run={async()=>{const result=await runtime.command('project.claim',{post_id:publicPost.id,slot_id:slot.id,slot_version:slot.rules_version,confirm:true});const current=await runtime.request<Entity>('/objects/'+result.id);if(current.data.status==='accepted')go({name:'community-post',id:result.project_id!});else runtime.report('申请已提交，发起者批准后即可开始工作')}}>{approval?'申请参与':'确认参与并开始'}</Action>}
   {owner&&entity&&<><button className="v277-secondary" onClick={()=>{setEditing(entity);setTitle(slot.title);setCriteria(slot.criteria);setCapacity(slot.capacity===null?'':String(slot.capacity));setRisk(slot.risk||'low');setParticipation(slot.participation||'open');setDeadline(slot.deadline?new Date(Date.parse(slot.deadline)-new Date(slot.deadline).getTimezoneOffset()*60000).toISOString().slice(0,16):'');setDepends(slot.depends_on||[])}}>编辑任务位</button>{slot.status==='open'&&<Action run={()=>runtime.command('project.slot.close',entityRef(entity))}>关闭任务位</Action>}</>}
  </article>;
 })}
 {owner&&project&&<details><summary>{editing?'编辑任务位':'添加任务位'}</summary><Field name="任务名称" value={title} onChange={setTitle}/><Field name="任务验收标准" value={criteria} onChange={setCriteria} area/><label className="v277-field">人数（留空表示不限）<input type="number" min="1" max="100" value={capacity} onChange={e=>setCapacity(e.target.value)}/></label><label className="v277-field">截止时间（可选）<input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><label className="v277-field">风险<select value={risk} onChange={e=>setRisk(e.target.value)}><option value="low">低风险、可撤销</option><option value="high">高风险、需审批</option></select></label><label className="v277-field">参与方式<select value={participation} onChange={e=>setParticipation(e.target.value)}><option value="open">符合条件可直接认领</option><option value="application">申请后批准</option></select></label><p>有限名额或高风险任务均需发起者批准。</p><p>前置任务</p>{slots.filter(slot=>slot.id!==editing?.id).map(slot=><label key={slot.id} style={{display:'block'}}><input type="checkbox" checked={depends.includes(slot.id)} onChange={e=>setDepends(old=>e.target.checked?[...old,slot.id]:old.filter(id=>id!==slot.id))}/>{displayTitle(slot.title,'')}</label>)}<Action disabled={!title.trim()||!criteria.trim()} run={async()=>{await runtime.command('project.slot.save',{...(editing?entityRef(editing):{}),project_id:project.id,title,criteria,capacity:capacity?Number(capacity):null,risk,participation,deadline:deadline?new Date(deadline).toISOString():null,depends_on:depends});setTitle('');setCriteria('');setDepends([]);setEditing(null)}}>保存任务位</Action><p>保存后点击上方“确认公开以上项目资料”，更新社区中的招募内容。</p></details>}
 </section>;
}
