"use client";
import {displayTitle} from "../../core/display-labels";
import {MarkdownContent} from '../../core/markdown-content';
import {finalReceipts} from '../../core/result-output';
import {ModuleStatus} from '../../core/module-status';
import {ProjectBoard} from './project-board';
import {useState} from 'react';
import {useRuntime,entityRef} from '../../core/runtime-context';
import {Action,Field} from '../../core/runtime-panels';
import {type Entity,text,statuses} from '../live/types';
import type {Screen} from '../../core/screen';
export function ProjectBriefEditor({project,published}:{project:Entity;published:boolean}){
 const r=useRuntime()!,owner=project.owner===r.snapshot?.user.id;
 const [title,setTitle]=useState(text(project,'title')),[goal,setGoal]=useState(text(project,'goal')),[basis,setBasis]=useState(text(project,'basis')),[criteria,setCriteria]=useState(text(project,'criteria')),[task,setTask]=useState(text(project,'task')),[participation,setParticipation]=useState(text(project,'participation')||'application'),[feeTerms,setFeeTerms]=useState(text(project,'fee_terms')),[deadlineMode,setDeadlineMode]=useState(text(project,'deadline_mode')||'none'),[deadline,setDeadline]=useState(text(project,'deadline')),[confirmed,setConfirmed]=useState(false);
 if(!owner)return null;
 const complete=[title,goal,basis,criteria,task,feeTerms].every(value=>value.trim())&&(deadlineMode==='none'||Boolean(deadline));
 const changed=title!==text(project,'title')||goal!==text(project,'goal')||basis!==text(project,'basis')||criteria!==text(project,'criteria')||task!==text(project,'task')||participation!==text(project,'participation')||feeTerms!==text(project,'fee_terms')||deadlineMode!==text(project,'deadline_mode')||deadline!==text(project,'deadline');
 return <section className="v277-edit-card"><h3>{published?'公开资料与招募':'公开预览与确认'}</h3><p>公开后，任何社区成员可看到下面的信息；工作副本、阶段过程与成员讨论只向项目成员开放。</p><article className="v277-edit-card"><h4>{displayTitle(title,'项目名称')}</h4><p>目标：{goal||'待补充'}</p><p>已有基础：{basis||'待补充'}</p><p>开放任务：{task||'待补充'}</p><p>验收：{criteria||'待补充'}</p><p>参与：{participation==='application'?'申请后由发起者批准':'确认本人承诺后参与'}</p><p>审核负责人：你</p><p>费用：{feeTerms||'待补充'}</p><p>截止：{deadlineMode==='none'?'不设截止':deadline||'待补充'}</p></article><details><summary>编辑共创资料</summary><Field name="项目名称" value={title} onChange={setTitle}/><Field name="共同目标" area value={goal} onChange={setGoal}/><Field name="已有基础（只填可公开内容）" area value={basis} onChange={setBasis}/><Field name="开放任务" area value={task} onChange={setTask}/><Field name="验收标准" area value={criteria} onChange={setCriteria}/><label className="v277-field">参与方式<select value={participation} onChange={event=>setParticipation(event.target.value)}><option value="application">申请后由发起者批准</option><option value="open">确认本人承诺后参与</option></select></label><Field name="费用说明" area value={feeTerms} onChange={setFeeTerms}/><label className="v277-field">截止设置<select value={deadlineMode} onChange={event=>setDeadlineMode(event.target.value)}><option value="none">不设截止</option><option value="date">指定日期</option></select></label>{deadlineMode==='date'&&<label className="v277-field">截止日期<input type="date" value={deadline} onChange={event=>setDeadline(event.target.value)}/></label>}<Action disabled={!complete||!changed} run={async()=>{await r.command('project.brief.update',{...entityRef(project),title,goal,basis,task,criteria,participation,public_scope:'brief',reviewer_id:project.owner,fee_terms:feeTerms,deadline_mode:deadlineMode,deadline});setConfirmed(false)}}>保存项目资料</Action></details><label><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>我已核对公开范围、任务、审核与费用</label><Action disabled={!complete||changed||!confirmed} run={async()=>{await r.command('project.publish_post',{...entityRef(project),confirm:true});setConfirmed(false)}}>{published?'确认更新公开招募':'确认公开发布招募'}</Action></section>;
}
function StageFeedback({project,stages}:{project:Entity;stages:Entity[]}){
 const r=useRuntime()!,s=r.snapshot!,active=stages.filter(stage=>stage.data.status==='shared');
 const [stageId,setStageId]=useState(''),[kind,setKind]=useState('review'),[content,setContent]=useState('');
 const selected=active.find(stage=>stage.id===stageId),comments=(s.objects.feedback||[]).filter(item=>item.space===project.id&&Boolean(item.data.stage_ref));
 return <section><h4>针对阶段版本的反馈</h4>{!active.length?<p>成员共享并审查过程稿后，就能在这里针对具体版本提出修改或确认。</p>:<><label className="v277-field">过程稿<select value={stageId} onChange={event=>setStageId(event.target.value)}><option value="">选择要反馈的阶段</option>{active.map(stage=><option key={stage.id} value={stage.id}>{displayTitle(text(stage,'title'),'阶段成果')} · {project.members?.find(member=>member.id===stage.owner)?.name||'成员'}</option>)}</select></label><label className="v277-field">反馈类型<select value={kind} onChange={event=>setKind(event.target.value)}><option value="review">核对与修改建议</option><option value="blocked">阻塞</option><option value="dependency">依赖变化</option><option value="progress">进展</option></select></label><Field name="针对这个版本的具体反馈" area value={content} onChange={setContent}/><Action disabled={!selected||!content.trim()} run={async()=>{await r.command('project.feedback',{id:project.id,stage_id:selected!.id,stage_version:selected!.version,kind,content});setContent('')}}>发送阶段反馈</Action></>}{comments.map(item=>{const ref=item.data.stage_ref as {id:string;version:number};const stage=stages.find(candidate=>candidate.id===ref.id);return <article className="v277-edit-card" key={item.id}><small>{project.members?.find(member=>member.id===item.owner)?.name||'成员'} · 针对 {stage?displayTitle(text(stage,'title'),'阶段成果'):'历史阶段'}{stage&&stage.version!==ref.version?'（已有新版本）':''}</small><MarkdownContent text={text(item,'content')}/></article>})}</section>;
}
function DispatchPublication({project}:{project:Entity}){
 const r=useRuntime()!,s=r.snapshot!;
 if(project.owner!==s.user.id)return null;
 const tasks=s.objects.task.filter(task=>task.data.dispatch_for===project.id&&task.data.status==='completed');
 const published=new Set(s.objects.feedback.filter(item=>item.space===project.id&&item.data.kind==='coordination').map(item=>String(item.data.task_id)));
 return <>{tasks.filter(task=>!published.has(task.id)).map(task=><Action key={task.id} run={()=>r.command('project.dispatch.publish',{id:project.id,task_id:task.id,confirm:true})}>共享已验收的协作安排</Action>)}</>;
}
export function ProjectWork({project,go,onBack}:{project:Entity;go:(screen:Screen)=>void;onBack:()=>void}){
 const r=useRuntime()!,s=r.snapshot!,owner=project.owner===s.user.id,[limit,setLimit]=useState(String((project.data.public_budget as {limit?:number})?.limit||3000)),[goal,setGoal]=useState(''),[reason,setReason]=useState(''),[discussion,setDiscussion]=useState(''),[feedbackKind,setFeedbackKind]=useState('progress');
 const stages=(s.objects.project_stage||[]).filter(x=>x.space===project.id);
 const discussions=(s.objects.feedback||[]).filter(item=>item.space===project.id&&!item.data.stage_ref&&['progress','blocked','dependency','coordination'].includes(String(item.data.kind))).sort((a,b)=>a.created.localeCompare(b.created));
 return <section className="v277-edit-card"><h3>共创过程</h3><ProjectBoard project={project}/><StageFeedback project={project} stages={stages}/><p>{project.data.status==='ended'?'项目已结束':'各成员在本人的副本中工作，审查后共享阶段成果。共享不等于提交或公开发布。'}</p>{Boolean(project.data.origin_release)&&<button onClick={()=>go({name:'knowledge-detail',id:text(project,'origin_release')})}>查看原作与署名</button>}<h4>项目讨论与进度</h4>{!discussions.length&&<p>还没有成员反馈。进展、阻塞和依赖变化会留在这个项目中。</p>}{discussions.map(item=><article className="v277-edit-card" key={item.id}><small>{project.members?.find(member=>member.id===item.owner)?.name||'项目成员'} · {{progress:'进展',blocked:'遇到阻塞',dependency:'依赖变化',coordination:'协作安排（待成员核对）'}[String(item.data.kind)]||'反馈'} · {new Date(item.created).toLocaleString('zh-CN')}</small><MarkdownContent text={text(item,'content')}/></article>)}{project.data.status==='active'&&<><label className="v277-field">反馈类型<select aria-label="共创反馈类型" value={feedbackKind} onChange={event=>setFeedbackKind(event.target.value)}><option value="progress">进展</option><option value="blocked">遇到阻塞</option><option value="dependency">依赖变化</option></select></label><Field name="向项目成员分享进度或问题" area value={discussion} onChange={setDiscussion}/><Action disabled={!discussion.trim()} run={async()=>{await r.command('project.feedback',{id:project.id,kind:feedbackKind,content:discussion});setDiscussion('')}}>发送到项目</Action></>}<h4>共享阶段成果</h4><ModuleStatus types={['project_stage']}>{stages.map(stage=><details key={stage.id}><summary>{displayTitle(text(stage,'title'),'')}{stage.data.status==='superseded'?'（已有更新，保留历史）':''} · {project.members?.find(m=>m.id===stage.owner)?.name}</summary><MarkdownContent text={text(stage,'content')}/><p>共享时间：{new Date(stage.created).toLocaleString('zh-CN')}</p></details>)}</ModuleStatus><h4>公共调度额度</h4><p>已使用 {Number(project.data.public_budget_used||0)} / {Number((project.data.public_budget as {limit?:number})?.limit||0)}。公共调度由发起者本人承担；成员工作使用各自额度。</p>{owner&&project.data.status==='active'&&<><Field name="本项目公共额度上限" type="number" value={limit} onChange={setLimit}/><Action run={()=>r.command('project.budget',{...entityRef(project),limit:Number(limit),confirm:true})}>确认使用本人额度</Action><Field name="本次需要协调的事项" area value={goal} onChange={setGoal}/><Action disabled={!goal.trim()||!project.data.public_budget} run={async()=>{const result=await r.command('project.dispatch',{id:project.id,goal,confirm:true,model_consent:true});go({name:'task',id:result.id})}}>准备临时调度任务，核对后启动</Action></>}<DispatchPublication project={project}/>{project.data.status==='active'&&<details><summary>{owner?'结束项目':'退出项目'}</summary><p>{owner?'停止招募与新执行，保留既有成果和历史。':'停止本人执行及后续读取，不代你提交未完成的副本。'}</p><Field name="说明" value={reason} onChange={setReason}/><Action run={async()=>{await r.command(owner?'project.end':'project.leave',{...entityRef(project),confirm:true,reason});if(!owner)onBack()}}>确认{owner?'结束':'退出'}</Action></details>}</section>;
}
export function CopyWork({copy,go}:{copy:Entity;go:(screen:Screen)=>void}){
 const r=useRuntime()!,s=r.snapshot!,[goal,setGoal]=useState(''),[title,setTitle]=useState(''),[reviewed,setReviewed]=useState(false),[system,setSystem]=useState('create');
 const task=s.objects.task.find(t=>t.id===copy.data.ai_task_id),run=s.objects.run.find(t=>t.id===task?.data.run_id),output=finalReceipts((run?.data.receipts||[]) as {output?:unknown;phase?:string}[]).find(x=>typeof x.output==='string')?.output;
 const stages=(s.objects.project_stage||[]).filter(x=>x.space===copy.data.project_id&&x.data.status==='shared');
 return <details><summary>用本人 AI 协作、共享阶段成果与文件</summary><p>AI 只在本人任务中生成结果，必须由本人检查并写入副本，随后仍需单独提交和发布。</p><Field name="本次希望完成的工作" area value={goal} onChange={setGoal}/><label className="v277-field">负责 Agent<select value={system} onChange={e=>setSystem(e.target.value)}>{s.systems.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><Action disabled={copy.data.status!=='draft'||!goal.trim()} run={async()=>{const result=await r.command('copy.ai_prepare',{...entityRef(copy),goal,system,confirm:true,model_consent:true});go({name:'task',id:result.id})}}>准备本人 AI 工作任务，核对后启动</Action>{task&&<p>{statuses[text(task,'status')]} <button onClick={()=>go({name:'task',id:task.id})}>查看工作结果</button></p>}{typeof output==='string'&&<><MarkdownContent text={output}/><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>已核对结果与副本，确认替换正文</label><Action disabled={!reviewed||copy.data.status!=='draft'} run={()=>r.command('copy.ai_apply',{...entityRef(copy),reviewed:true})}>写入本人副本，暂不提交</Action></>}
 <h4>引用共享阶段版本</h4>{stages.map(stage=><div key={stage.id}><p>{displayTitle(text(stage,'title'),'')}</p><Action disabled={copy.data.status!=='draft'} run={()=>r.command('stage.depend',{...entityRef(copy),stage_id:stage.id})}>将此版本作为工作依据</Action></div>)}<h4>共享本人已保存的阶段内容</h4><Field name="阶段标题" value={title} onChange={setTitle}/><p>共享范围为当前项目成员，先核对正文不含未授权的私人资料；这不会正式提交贡献。</p><Action disabled={copy.data.status!=='draft'||!title.trim()||!text(copy,'content').trim()} run={()=>r.command('copy.stage',{...entityRef(copy),title,reviewed:true})}>已审查，确认共享当前保存版</Action><FilesEditor copy={copy}/>{Boolean((copy.data.unresolved_conflicts as string[]|undefined)?.length)&&<section><p role="alert">待解决冲突：{(copy.data.unresolved_conflicts as string[]).join("、")}。请对照上游修改文件，保存后再确认。</p><Action run={()=>r.command('copy.resolve',{...entityRef(copy),reviewed:true})}>已逐文件核对，确认保留当前保存内容</Action></section>}</details>;
}
function FilesEditor({copy}:{copy:Entity}){
 const r=useRuntime()!,[base,setBase]=useState(copy.version),[files,setFiles]=useState<Record<string,string>>(copy.data.files as Record<string,string>||{}),[path,setPath]=useState('');
 const stale=base!==copy.version;
 return <details><summary>项目文件 · {Object.keys(files).length} 个</summary><p>文本文件保留版本，采纳时逐文件合并；同一文件冲突不会覆盖上游修改。</p>{stale&&<button onClick={()=>{setFiles(copy.data.files as Record<string,string>||{});setBase(copy.version)}}>载入最新文件后编辑</button>}{Object.entries(files).map(([name,content])=><details key={name}><summary>{name}</summary><Field name={name} area value={content} onChange={value=>setFiles(old=>({...old,[name]:value}))}/><button onClick={()=>setFiles(old=>Object.fromEntries(Object.entries(old).filter(([key])=>key!==name)))}>移除此文件</button></details>)}<Field name="新增文件路径，如 notes/说明.md" value={path} onChange={setPath}/><button disabled={!path.trim()||path in files} onClick={()=>{setFiles(old=>({...old,[path]:''}));setPath('')}}>添加文件</button><Action disabled={stale||copy.data.status!=='draft'} run={async()=>{await r.command('copy.files',{...entityRef(copy),files});const current=await r.request<Entity>('/objects/'+copy.id);setBase(current.version);setFiles(current.data.files as Record<string,string>||{})}}>保存文件修改</Action></details>;
}
